index.html
style.css

When you switch dark for the first time, the image will not appear immediately because `flashlight.png` takes time to load.
Adding this class will start to load `flashlight.png` as soon as you enter it without affecting the main interface.

perf: optimize flashlight load

---

_posts/2021-02-24-monitors-mac.md

- changed MacBook Pro 16 to have the official production year (2019). There was no update to the 16-inch MacBook in 2020. Official list of products from Apple: https://support.apple.com/en-us/HT201300
- added Acer XB3 Predator compatibility

Acer Predator XB3 compatibility

---

_posts/2021-03-29-font-size.md

This patch fixes the typo in `Let't`.

typo: Change `Let’t` to `Let’s`.

---

_posts/2021-02-24-monitors-mac.md

This monitor also works with the 16" MacBook Pro, although I don’t have the screenshots at the moment.

Add LG 27GN950-B for MacBook Air M1 2020

---

_posts/2021-02-24-monitors-mac.md

This PR adds compatibility information for MacBook Pro (16-inch, 2019) w/ Radeon Pro 5300M and Acer NITRO XV3 (XV273K Pbmiipphzx).

MacBook Pro (16-inch, 2019) and Acer NITRO V3

---

_posts/2021-02-24-monitors-mac.md

34GN850-B work fine with 144 on Mac if use displayport -> usb c

New LG monitor 34GN850-B

---

_posts/2021-02-24-monitors-mac.md

The Gigabyte M28U runs at 144Hz over USB-C on both the MBP and the monitor.
Not entirely sure what's up with the reported resolution of the monitor, since it's definitely 4k. Might be due to the scaling settings that I'm currently using.

monitors-mac: Add Gigabyte M28U

---

_posts/2021-02-24-monitors-mac.md

Also:
- Fixed the names of some Macs following the "Name (Screen-Size, Year) w/ Graphics-Card" pattern
- Fixed some monitor names following the "Brand Marketing-Name Model" pattern
- Ordered monitor names alphabetically
- Fixed names of some graphics cards, sourcing the official Apple specs

Add MacBook Pro (16-inch, 2019) w/ Radeon Pro 5500M  / Acer NITRO XV3

---

_posts/2021-02-24-monitors-mac.md

Unfortunately, I failed to make the monitor work at 4K@144Hz using c2c cable and c2DP cable. I found that the graphics card can only support DP1.2 protocol in Windows. I don't know if Apple has made a restriction. Because MBP 15 2018 and MBP 15 2019 are exactly the same on the graphics card and the Thunderbolt 3 main control chip. If you can successfully use 4K@144Hz on MBP 15 2018, please let me know how to use it, or if anyone knows why it can’t be used, please let me know.

Add Gigabyte M28U for MBP 15 2018

---

_posts/2021-02-24-monitors-mac.md

I've been running this setup for over a year on a KVM. It only works without scaling, but I don't know if any mac hardware works with scaling and 120hz. When I turn scaling on the display flickers between being off and displaying a black screen.
He's some screenshots:

Added Mac Pro (2019) with Acer X27

---

_layouts/post.html

Current behaviour:
Reader mode is not active for the https://tonsky.me/blog/disenchantment/ post (Safari desktop, Safari iOs).
Expected behaviour:
Reader mode is active for the https://tonsky.me/blog/disenchantment/ post
Explanation of the issue:
Safari Reader mode algorithm may be confused with UI-ish elements like translations list. Making layout more semantic usually solves the issue.
Proposed changes:
- Replace post wrapper `div` tag with the `article` tag. This will help the Safari Reader mode algorithm to discover post content.

Help the Safari Reader mode algorithm

---

_layouts/default.html

I dare to propose a tiny fix to the website. `div` tags are not self-closing and must be accompanied by a closing `</div>` tag.
I don't see any visible issues with this, browsers are smart enough to handle it. But it could potentially help robots better understand the markup of a site. For example, Safari Reader mode (see related PR https://github.com/tonsky/tonsky.github.io/pull/46). So don't take this PR as a stupid nag.

Fix: Add a closing div tag

---

_posts/2021-02-24-monitors-mac.md

Add MacBook Pro (M1 Pro, 14-inch, 2021) and Acer Nitro XV3

---

_posts/2021-02-24-monitors-mac.md

Connected via USB-C to DisplayPort cable

Add MacBook Pro (M1 Max, 16-inch, 2021) and LG UltraGear 27GP950-B

---

_posts/2021-02-24-monitors-mac.md

This screen work for Macbook Pro 16" with M1 Pro chip. I'm using USB-C to DisplayPort 1.4 cable:
With my old Macbook Pro 15" 2018, the refresh rate is only 120Hz with USB-C to DisplayPort 1.4 cable:

Add Macbook Pro 16" M1 Pro and Macbook Pro 15" 2018 with Gigabyte M32U

---

_posts/2021-02-24-monitors-mac.md

I was able to achieve:
- 4k @120Hz with a good DP 1.4 <-> USB-C cable
- 4k @60Hz with a good HDMI 2.0 cable.

Add Acer Predator XB3 to the 2021 M1 Pro 14-inch model

---

_posts/2021-02-24-monitors-mac.md

I recently bought the [XB283K](https://www.amazon.com/Acer-Predator-KVbmiipruzx-Agile-Splendor-Compatible/dp/B09HN33HRD) to use with my M1 Pro  14" MBP and it's working great!
Screenshots requested:

Added XB283K

---

_posts/2021-02-24-monitors-mac.md

Hey I recently bought a Type-C2DP1.4 Cable and it's works very well with my MacBook Pro 2020 13-inch with Acer Predator XB283K KV. Everything works fine.

update XB283K for MacBook Pro 13-inch 2020 Intel model.

---

_posts/2021-02-24-monitors-mac.md

Thanks for maintaining this list. It was helpful. Here's my contribution.

Gigabye M28U works with MacBook Air (M1, 2020)

---

_posts/2021-02-24-monitors-mac.md

Using USB-C to Display Port cable (the cable supports 4K 144hz on my M1 Macbook Air, so it's all good).

Dell G3223Q doesn't work with 16-inch MBP 2019

---

_posts/2021-02-24-monitors-mac.md

Add negative result for MacBook Pro (16-inch, 2019) w/ Radeon Pro 5500M and LG CX 4K OLED TV (55-inch, 2020).
Bummer.

Add negative result for MacBook Pro (16-inch, 2019) w/ Radeon Pro 5500M

---

_posts/2021-02-24-monitors-mac.md

MacBook Air (M1, 2020)
- Asus ROG Swift PG32UQ
- Gigabyte M32U
MacBook Pro (M1 Max, 16-inch, 2021)
- Asus ROG Swift PG32UQ
- Gigabyte M32U
Mac Studio (M1 Max, 2022)
- Asus ROG Swift PG32UQ

Added Multiple Compatible Displays & Macs.

---

_posts/2021-02-24-monitors-mac.md

4K @ 144 Hz using CableMatters USB-C - DP cable.
NB: Did not work on macOS 12.5.1, only DP 1.2 would function.
Pro:
Air:

Samsung G70A 28" works with MBP14" M1 Max & MBA M1

---

_posts/2021-02-24-monitors-mac.md

Add Samsung Odyssey G7 S28AG70 for a MacBook Pro (M1 Pro, 16-inch, 2021)

Add Odyssey G7 for MacBook Pro

---

_posts/2021-02-24-monitors-mac.md

Added the Samsung Odyssey Neo G7 (LS32BG75) for the 16 inch MacBook Pro M1 Max (2021). Works with 4k 120hz over DisplayPort.

Add Odyssey Neo G7 for a MacBook
